name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Start app
      id: start-app
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Start app
        setup-command: npm install
        command: npm run dev
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        START-APP_RESULTS: "${{steps.start-app.outputs.result}}"
      with:
        runners: start-app
